### ISSUE TITLE
Installed. And now?

### ISSUE THREAD

**Issue by vandenbogerd** [erik73/addon-steve#154]
# Problem/Motivation

I installed this. Together with MariaDB, after reading closed issues here. 
And now?

I see a device “Steve”. But no URL or anything. 

## Expected behavior

This repo working :)

## Actual behavior

Can’t make it work?

## Steps to reproduce

Install MariaDB
Install Steve
Reboot

## Proposed changes

Maybe a little bit more explanation in the readme….

**Comment by erik73** [comment]
Hi.
This add-on is an experiment, and I have not yet documented it.
I have not solved the ingress functionality.
What you need to do is to use your browser and point it to your HomeAssistant-ip on port 8180.
For example: http://192.168.x.x:8180
You should then reach the SteVe web interface.

**Comment by vandenbogerd** [comment]
Thank you!
