### ISSUE TITLE
Problem with properties file

### ISSUE THREAD

**Issue by mkbrown** [erik73/addon-steve#213]
# Problem/Motivation

```
[14:35:17] INFO: SteVe stopped, restarting...
[14:35:18] INFO: Starting SteVe....
[INFO ] 2023-09-10 14:35:19,481 de.rwth.idsg.steve.utils.PropertiesFileLoader (main) - Hint: The Java system property 'main.properties' can be set to point to an external properties file, which will be prioritized over the bundled one
[INFO ] 2023-09-10 14:35:19,603 de.rwth.idsg.steve.Application (main) - Loaded the properties. Starting with the 'PROD' profile
[14:35:19] INFO: SteVe stopped, restarting...
[14:35:20] INFO: Starting SteVe....
[INFO ] 2023-09-10 14:35:21,896 de.rwth.idsg.steve.utils.PropertiesFileLoader (main) - Hint: The Java system property 'main.properties' can be set to point to an external properties file, which will be prioritized over the bundled one
[INFO ] 2023-09-10 14:35:22,017 de.rwth.idsg.steve.Application (main) - Loaded the properties. Starting with the 'PROD' profile
[14:35:22] INFO: SteVe stopped, restarting... 

```

## Expected behavior

App loads properties correctly.

## Actual behavior

App builds, but keeps restarting with the indicated error.

## Steps to reproduce

Steve Addon Version 2.0.11, 
HomeAssistant 2023.9.1, supervisor-2023.08.3
MariaDB Addon version 2.6.1.

**Comment by erik73** [comment]
How much memory do you have in your HA host?

**Comment by mkbrown** [comment]
It’s a HASSOS VM with 4G of memory currently assigned. Can up it if need be, but RAM usage is showing as low for all addons and core.

For testing the memory, I doubled the RAM to 8G.  Same problem with the properties file.

**Comment by erik73** [comment]
Ok, I just tried with a VM myself, and it worked as expected.

Some suggestions:
Install the phpMyAdmin add-on and to verify that the stevedb has been created in MariaDB. 
Have you tried to remove the add-on and reinstall it to force it to compile again?

A last thing to do is to drop the stevedb from MariaDB (using phpMyAdmin), remove the SteVe add-on and start from scratch.

Please report back with your findings.

**Comment by mkbrown** [comment]
Ok, it took a few uninstalls and db drops and reinstalls, but I was finally successful, and got my Charger connecting up. Grizzl-e Smart v2 as an FYI.  Thanks for your assistance!

Might want to update the install note to recommend 8G of RAM with the add-on. 4G with other addons might be a bit tight…
