### ISSUE TITLE
Can't init addon

### ISSUE THREAD

**Issue by angelsanchezz** [erik73/addon-steve#36]
# Problem/Motivation

Can't init the addon

## Expected behavior

Initialice

## Actual behavior

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: SteVe
 OCPP server for EV charging stations
-----------------------------------------------------------
 Add-on version: 1.2.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.12  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2021.3.3
 Home Assistant Supervisor: 2021.03.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-create-config.sh: executing... 
[19:52:39] ERROR: Got unexpected response from the API: Service not enabled
[cont-init.d] 10-create-config.sh: exited 139.
[cont-finish.d] executing container finish scripts...
[cont-finish.d] 99-message.sh: executing... 
-----------------------------------------------------------
                Oops! Something went wrong.

 We are so sorry, but something went terribly wrong when
 starting or running this add-on.
 
 Be sure to check the log above, line by line, for hints.
-----------------------------------------------------------
[cont-finish.d] 99-message.sh: exited 0.
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

**Comment by erik73** [comment]
Hi.

You need to have the Official MariaDB add-on installed and running. 
SteVe will create a database on startup to store its data.
