### ISSUE TITLE
Repositories Add in HA not possible

### ISSUE THREAD

**Issue by thecem** [erik73/addon-steve#75]
# Problem/Motivation
Could not add addon repository.
> (Why the issue was filed)

## Expected behavior
Add addon repo via repositories add in Home Assiatant
> (What you expected to happen)

## Actual behavior
![grafik](https://user-images.githubusercontent.com/46648579/130322448-cae9366a-00d1-4446-bd4e-c0433f9efc25.png)

> (What actually happened)

## Steps to reproduce

> (How can someone else make/see it happen)

## Proposed changes

> (If you have a proposed change, workaround or fix,
> describe the rationale behind it)

**Comment by thecem** [comment]
```
21-08-21 15:00:06 INFO (MainThread) [supervisor.store.git] Cloning add-on https://github.com/erik73/addon-steve repository
21-08-21 15:00:07 ERROR (MainThread) [supervisor.store] https://github.com/erik73/addon-steve is not a valid add-on repository
```

**Comment by erik73** [comment]
This is the name of the repo: https://github.com/erik73/hassio-addons
